name: Build Image
on:
  workflow_dispatch:
  watch:
    types: [started]
jobs:
  build:
      runs-on: ubuntu-latest
      if: github.event.repository.owner.id == github.event.sender.id
      name: Build image job
      steps:
          - name: Checkout master
            uses: actions/checkout@master
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            if: startsWith(github.ref, 'refs/tags/')
            with:
              publish: true
              imageName: goukey/qiandao # dockerid/imageName
              platform: linux/arm64,linux/amd64,linux/arm/v7 # 你准备构建的镜像平台
              tag: $(date +"%Y%m%d"),latest
              dockerUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
              dockerPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword
